# Documentation: http://docs.travis-ci.com/user/languages/julia/
notifications:
  email: false

language: julia

os:
  - linux

julia:
  - 1.3

before_install:
- julia --color=yes -e 'using Pkg; pkg"dev https://github.com/Juice-jl/LogicCircuits.jl"; pkg"dev https://github.com/Juice-jl/ProbabilisticCircuits.jl"'
- julia --color=yes --project=./test -e 'using Pkg; "dev ."'
- julia --color=yes --project=./test -e 'using Pkg; Pkg.activate(); Pkg.instantiate(); Pkg.precompile()'
- julia --color=yes --project=. -e 'using Pkg; Pkg.add("Jive")'

script:
- julia --color=yes --project=. -p2 test/runtests.jl
