# Documentation: http://docs.travis-ci.com/user/languages/julia/
notifications:
  email: false

language: julia

os:
  - linux

julia:
  - 1.3

before_install:
- julia --color=yes --project=. -e 'using Pkg; pkg"dev https://github.com/Juice-jl/LogicCircuits.jl"'
- julia --color=yes --project=. -e 'using Pkg; pkg"dev https://github.com/Juice-jl/ProbabilisticCircuits.jl"'
- julia --color=yes --project=. -e 'using Pkg; pkg"add DataStructures"'
- julia --color=yes --project=. -e 'using Pkg; pkg"precompile"'

script:
-              julia --color=yes --project=. -p2 test/runtests.jl
- JIVE_PROCS=2 julia --color=yes --project=. -e 'using Pkg; Pkg.test()'
